### PR TITLE
add logging system

### PR DESCRIPTION
**Pull request by senceryazici**
Previous usage was implementing a way to obtain topics from a yaml file. With this approach we can filter the topics with regular expressions. I've excluded topics end with `image_raw`. Can you test this with a system where camera is running and make sure it does not record the `image_raw` topics, but record rest of them @canerdev

### CODE REVIEW

**Comment by canerdev** [comment]
> Previous usage was implementing a way to obtain topics from a yaml file. With this approach we can filter the topics with regular expressions. I've excluded topics end with `image_raw`. Can you test this with a system where camera is running and make sure it does not record the `image_raw` topics, but record rest of them @canerdev

will be able to work on it after 1st week of june

**Comment by senceryazici** [comment]
@YunusDiler proceed with hardware test on this please. I've excluded all topics that contain `image_raw`

**Comment by canerdev** [comment]
> @YunusDiler proceed with hardware test on this please. I've excluded all topics that contain `image_raw`

i think this is done last week and it works as expected. @senceryazici

**Comment by senceryazici** [comment]
The current implementation does not exclude "image_rect_color" etc etc. So we still have to find out every topic name that has type of "sensor_msgs/Image"

**Comment by ozanhakantunca** [comment]
These are the topics in a bag file @senceryazici 

/turquoise/cameras/cam_front/image_color                                                     1 msg     : sensor_msgs/Image 
/turquoise/cameras/cam_front/image_mono                                                      4 msgs    : sensor_msgs/Image 
/turquoise/cameras/cam_front/image_rect                                                      3 msgs    : sensor_msgs/Image 
/turquoise/cameras/cam_front/image_rect_color                                                1 msg     : sensor_msgs/Image

**Comment by senceryazici** [comment]
Looks like `.*\/image_[^\/]*$` is good

**Pull request merged**
